# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: Aprendiendo Javascript
description: > # this means to ignore newlines until "email:"
   Este blog contiene una serie de artículos que me han ayudado a mejorar mis conocimientos de Javascript.<br /> Si crees que puedes aportar algo para mejorarlo no dudes en hacer una pull request.
email: dave74@gmail.com
#blog logo
logo: "assets/images/jsblog_logo.jpg"
# blog cover
cover: "assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'David García'
author: 'David García'
author_image: "assets/images/author.jpg"
permalink: /:title

paginate:	5

url: "http://davecarter.me" # the base hostname & protocol for your site
baseurl: "/"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/d4vecarter
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/davecarter
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
